create TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create TABLE IF NOT EXISTS item_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR(512) NOT NULL,
  requestor_id BIGINT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT pk_item_requests PRIMARY KEY (id),
  CONSTRAINT fk_item_requests_to_users FOREIGN KEY(requestor_id) REFERENCES users(id)
);

create TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  owner_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(512),
  available BOOLEAN NOT NULL DEFAULT false,
  request_id BIGINT,
  CONSTRAINT pk_items PRIMARY KEY (id),
  CONSTRAINT fk_items_to_users FOREIGN KEY(owner_id) REFERENCES users(id) ON delete CASCADE,
  CONSTRAINT fk_items_to_requests FOREIGN KEY (request_id) REFERENCES item_requests(id)
);

